# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://zhaojkun.github.io
date_format: "ordinal"
title: 点滴
subtitle: ""
description: "zhaojkun's blog"
keywords: 源代码, golang, python
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 4

# ---------------- #
#      Author      #
# ---------------- #
author: Jiangkun Zhao
organization: Eleme, Inc.
organization_url: http://www.ele.me
github_username: zhaojkun
location: Shanghai, China
email: zhaojk90@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: zhaojkun/zhaojkun.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
disqus_username:

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: xxxxxxx

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [C, C++, Python, Go]
skill_research: [分布式, 存储]
